apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountmicroservice
  labels:
    app: accountmicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountmicroservice
  template:
    metadata:
      labels:
        app: accountmicroservice
    spec:
      containers:
      - name: accountmicroservice-container
        image: federicoand98/account-microservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "128Mi"
            cpu: "0.3"
